# This is a basic workflow to help you get started with Actions

#ame: CI

# Controls when the workflow will run
  # Tri???s the workflow on push or pull request events but only for the "main" branch
  #ush:
    #anches: [ "main" ]
  #_request:
    #ranches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  #rkflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
#:
  # This workflow contains a single job called "build"
  #ild:
    
    #The type of runner that the job will run on
    #ns-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the jo
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
      
        name: Android CI

on:
  push:
    branches:
      - main
      - tooling-api

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build debug apk
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: :app:clean :app:build
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true

      - name: Generate translation report
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: :app:checkTranslations
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true

      - name: Upload APK
        uses: actions/upload-artifact@v2
        if: ${{ !github.head_ref }}
        with:
          name: apk-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload translation report
        uses: actions/upload-artifact@v2
        if: ${{ !github.head_ref }}
        with:
          name: translation-report
          path: build/translation-reports/


      
      
        
          
          
